### ISSUE TITLE
IO closed stream

### ISSUE THREAD

**Issue by kcollignon** [georgediaz88/fun_sftp#10]
Hello

I am having issues when I upload a file to an SFTP server, the file successfully places on the server however I am getting a "Closed Stream" error returned. Would you have any idea what causes this or how to resolve it? Thanks!

```ruby
begin
  conn = SFTPClient.new(details)
  if conn
    conn.upload!(@file_path, "#{@connection.connection_path}/#{@file_name}")
  end
rescue Net::SFTP::StatusException => e
  raise e
 end
```

**Comment by georgediaz88** [comment]
@kcollignon , sorry for the delay. What version of Ruby are you using and fun_sftp version? This will help me try on my end and assess the issue. Thx.

**Comment by georgediaz88** [comment]
Closing due to no response.
