### ISSUE TITLE
Question: How can I keep SFTP connection active between AJAX calls?

### ISSUE THREAD

**Issue by crysper** [georgediaz88/fun_sftp#4]
I used a global variable as a connection pool, but we switched to multi-threaded environment and doesn't work anymore.

Do you have an idea of how can I keep the connection alive between different HTTP request and threads?

Thanks

**Comment by georgediaz88** [comment]
@crysper,

So, global variables in general are known to cause some issues when used in a multi-threaded environment. A thread-safe way may be to just reinitialize the connection when used in the code.

For example, each time reinitialize the connection like such:

```ruby
conn = SFTPClient.new(server, username, password)
# the `.new` above should achieve that
```

Do you see any problems doing it this way? If you need additional help, please paste some sample code and I'd be glad to take a look and make any further suggestions.

Thanks,
George

**Comment by crysper** [comment]
Thanks for the reply.

The issue is speed and connection management. Each of our users has a SFTP account linked and can connect to their server. For example if they need to upload 20 items, it may require a more than 3 new SFTP connections initalizations in a multi-threaded environment, which takes a long time. It's also hard to disconnect all of them when there are multiple connections in different threads.

**Comment by georgediaz88** [comment]
Okay. This may be a more general ruby thing to solve . I haven't heard issues around this gem just yet around speed / connection issues. I'm glad you're bringing it up though.

The `fun-sftp` gem is a wrapper around Ruby's Net::SFTP library. So, anything you can do here, should funnel down to this library: http://www.rubydoc.info/gems/net-sftp/2.0.5/Net/SFTP. If there's a feature you need added to this gem from that library, we can surely add if it helps.

As for your use case, the fact that it worked in a single-threaded environment how you wanted seems promising and is now just a matter of figuring out for a multi-threaded environment, correct? 

So, perhaps sharing information across threads is what you need? It's hard for me to truly understand the problem at whole without some kind of sample code -- here's a link that may help give you some inspiration with how folks used the `ConnectionPool` to spread connections: http://stackoverflow.com/questions/28113940/what-is-the-best-way-to-use-redis-in-a-multi-threaded-rails-environment-puma.  Hope this helps.

**Comment by georgediaz88** [comment]
@crysper were you able to find a workaround? I can close this issue if you did.

**Comment by georgediaz88** [comment]
Closing due to no response.
