### ISSUE TITLE
File incorrectly identified as a Directory using Windows CoreSFTP server

### ISSUE THREAD

**Issue by dugsmith** [georgediaz88/fun_sftp#6]
I'm having a difficult issue using FunSftp, where unfortunately, our test SFTP server is a Linux server with OpenSSH, while the production server is Windows-based running CoreFTP. 

Here's a snapshot of my usage:
```
conn = SFTPClient.new(ENV['SFTP_HOST'], ENV['SFTP_USERNAME'], nil,
                     :port => ENV['SFTP_PORT'], :password => ENV['SFTP_PASSWORD'],
                     :non_interactive => true)
conn.chdir(ENV['SFTP_DIR'])
files = conn.glob('.', filename_pattern)
files.each do |file|
  conn.download!(file, local_path)
end
```

Against a Linux SFTP server, this works great. Against a Windows server, the code behind `conn.download!` identifies the `file` as a Directory, creates a directory locally in the local path with the name of the file, and then tries to download the file from within a directory. It fails that attempt. 

Digging into the [`download!` method here](https://github.com/georgediaz88/fun_sftp/blob/master/lib/fun_sftp.rb#L50), I see it makes the download recursive if `has_directory?` returns true. On Windows, `has_directory?`'s call through `Net::SFTP` incorrectly returns the filename of the file I'm trying to download instead of throwing the `Net::SFTP::StatusException` like it does on Linux.

If the `download!` method supported overriding the `recursive` method, that would be a workaround. But, maybe there's something else going on behind the scenes.

**Comment by georgediaz88** [comment]
@dugsmith, sorry for the delay.

Unfortunately, I haven't done much testing of this gem on a Windows server -- it's been purely Linux-based at that moment. Perhaps, there is something going on behind the scenes as you mentioned but I'd have to test that out to confirm.

In the meantime, I can make the options, `recursive` in your case, configurable from the method-level as you suggested to keep you moving.

Let me know if you're still in need of this change and I can add that code OR feel free to make a pull request yourself if you're feeling eager. Thanks.

**Comment by dugsmith** [comment]
@georgediaz88 Thank you for the reply and for your work on this gem. I would appreciate you allowing `recursive` to be configurable.

**Comment by georgediaz88** [comment]
@dugsmith , okay you're all set! Please use version "1.1.2" which has the requested change allowing you to now do: `conn.download!(file, local_path, recursive: false)`

pull request reference: https://github.com/georgediaz88/fun_sftp/pull/7

Thanks!
