### ISSUE TITLE
NoMethodError: undefined method 'Pathname' when calling chdir

### ISSUE THREAD

**Issue by menge101** [georgediaz88/fun_sftp#9]
I created a PR for this: https://github.com/georgediaz88/fun_sftp/pull/8

On ruby-2.4.2 I observed that the Pathname was undefined within the SftpClient class.

I also observed that it IS defined when the tests are run.  I couldn't figure out the discrepancy between the two situations.  But I did observe that requiring pathname solved my issue.

**Comment by georgediaz88** [comment]
Just released fun_sftp version 1.1.3 which includes this changes. Thanks again, @menge101 !
